
import { Language } from './types';

export const BOARD_SIZE = 8;

export const TRANSLATIONS: Record<Language, any> = {
  tr: {
    title: 'Patnos Dama',
    start: 'Oyuna Başla',
    rules: 'Kurallar',
    rulesTitle: 'Patnos Daması Kuralları',
    rule1: 'Taşlar ileri, sağa ve sola bir kare hareket eder (Geri gidemez).',
    rule2: 'Taş yemek zorunludur. Birden fazla seçenek varsa en çok taş yenecek yol seçilmelidir.',
    rule3: 'Karşı sıraya ulaşan taş "Dama" (Şah) olur. Dama her yöne istediği kadar gidebilir.',
    rule4: 'Dama taşları da en çok taş yeme kuralına tabidir.',
    namePlaceholder: 'Adınızı yazın...',
    difficulty: 'Zorluk Seviyesi',
    easy: 'Kolay',
    medium: 'Orta',
    hard: 'Zor',
    turn: 'Sıra:',
    blue: 'Mavi (Siz)',
    yellow: 'Sarı (Rakip)',
    winner: 'Kazanan:',
    draw: 'Beraberlik!',
    playAgain: 'Tekrar Oyna',
    timeLeft: 'Kalan Süre:',
    backToMenu: 'Menüye Dön',
    selectLang: 'Ziman / Dil',
    welcome: 'Hoşgeldiniz',
    playerLabel: 'Hamle Süresi',
    waiting: 'Bekliyor',
    thinking: 'Düşünüyor...',
  },
  ku: {
    title: 'Patnos Dama',
    start: 'Dest pê bike',
    rules: 'Rêzik',
    rulesTitle: 'Rêzikên Damaya Kurdî/Tirkî',
    rule1: 'Kevir ber bi pêş, rast û çep ve diçin (Paşve naçin).',
    rule2: 'Xwarina keviran mecbûrî ye. Heke çend rê hebin, divê rêya herî zêde kevir tê de têne xwarin were hilbijartin.',
    rule3: 'Kevirê ku digihîje rêza dawî dibe "Dama". Dama dikare her alî ve biçe.',
    rule4: 'Kevirên Dama jî li gorî rêzika xwarina herî zêde ne.',
    namePlaceholder: 'Navê xwe binivîse...',
    difficulty: 'Asta Zehmetiyê',
    easy: 'Hêsan',
    medium: 'Navîn',
    hard: 'Zehmet',
    turn: 'Dor:',
    blue: 'Şîn (Hûn)',
    yellow: 'Zerd (Reqîb)',
    winner: 'Serketî:',
    draw: 'Wekhevî!',
    playAgain: 'Dîsa Bilîze',
    timeLeft: 'Dema Mayî:',
    backToMenu: 'Vegere Menuyê',
    selectLang: 'Ziman / Dil',
    welcome: 'Bi xêr hatî',
    playerLabel: 'Lîstikvan',
    waiting: 'Li benda ye',
    thinking: 'Difikire...',
  }
};
